name: sense
eescription: Use your ScientISST Sense device on your smartphone.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bluetooth_enable:
    git:
      url: https://github.com/huitingyeong/bluetooth_enable
  charts_flutter: ^0.11.0
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  flutter_isolate: ^2.0.0
  flutter_spinkit: ^5.0.0
  intl: ^0.17.0
  location: ^4.3.0
  open_file: ^3.2.1
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2
  provider: ^5.0.0
  scientisst_sense:
    path: /home/robot/Documents/ScientISST/sense/apis/api-flutter
    #git:
      #url: https://github.com/scientisst/scientisst-sense-api-flutter
  shared_preferences: ^2.0.6
  slider_button:
    git:
      url: https://github.com/Shiba-Kar/Slider-Button.git
      ref: master
  watcher: ^1.0.0

dev_dependencies:
  flutter_native_splash: ^1.2.0
  flutter_test:
    sdk: flutter
  lint: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
